bqsr_rounds: 0
units: .test/config/units.tsv
chromosomes: .test/config/chromosomes.tsv
scaffold_groups: .test/config/scaffold_groups.tsv

# this is the default value for the first GenomicsDBImport run.
# If you want to change it, you should typically change it
# on the command line.
genomics_db_import_num: 0


# eric modified this to be able to easily handle genomes of non-model
# organisms that are not yet on enseml, etc.
ref:
  # name of the species.  (will simply be put in the SnpEff config).
  # Put underscores for spaces
  species_name: Oncorhynchus_tsawytscha
  # name you want to use for the genome version
  genome_version_name: Otsh_v2_reduced
  # the URL where this can be downloaded, if public and easy to
  # get with wget.  If not, then you should hand-download
  # genome.fasta and genome.gff or genome.gtf
  genome_url: https://github.com/eriqande/mega-non-model-wgs-snakeflow/raw/main/.test/genome/mini-test-genome.fna.gz
  # if there is a GFF or GTF file, they have to have a .gff or
  # .gtf extension.  This where you put the URL for it
  gff_or_gtf_url: ""


filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

processing:
  remove-duplicates: true
  # Uncomment and point to a bed file with, e.g., captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals.
  restrict-regions: chr24_26_28.bed
  # If regions are restricted, uncomment this to enlarge them by the given value in order to include
  # flanking areas.
  # region-padding: 100

params:
  gatk:
    HaplotypeCaller: ""
    BaseRecalibrator: ""
    GenotypeGVCFs: ""
    VariantRecalibrator: ""
  picard:
    MarkDuplicates: " --TAGGING_POLICY All --CREATE_INDEX "
  trimmomatic:
    pe:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "ILLUMINACLIP:resources/adapters/TruSeq3-PE-2.fa:2:30:10"
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
    se:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
  vep:
    plugins:
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      - LoFtool
    # extra command line arguments (e.g. --sift, see docs)
    extra: ""
