set-threads:
  map_reads: 4
  realigner_target_creator: 4
  genomics_db_import_chromosomes: 2
  genomics_db_import_scaffold_groups: 2
  genomics_db2vcf_scattered: 2
set-resources:
  map_reads:
    mem_mb: 14800
  map_reads:
    time: "23:59:59"
  make_gvcf_sections:
    mem_mb: 3600
  make_gvcf_sections:
    time: "23:59:59"
  genomics_db_import_chromosomes:
    mem_mb: 7400
  genomics_db_import_chromosomes:
    time: "23:59:59"
  genomics_db_import_scaffold_groups:
    mem_mb: 11000
  genomics_db_import_scaffold_groups:
    time: "23:59:59"
  genomics_db2vcf_scattered:
    mem_mb: 11000
  genomics_db2vcf_scattered:
    time: "23:59:59"
  multiqc_dir:
    mem_mb: 37000
  bwa_index:
    mem_mb: 37000
  realigner_target_creator:
    mem_mb: 14800
