cluster:
  mkdir -p results/slurm_logs/{rule} &&
  sbatch
    --partition=amilan128c,amilan,csu
    --qos=normal
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=results/slurm_logs/{rule}/{rule}-{wildcards}-%j.out
    --error=results/slurm_logs/{rule}/{rule}-{wildcards}-%j.err
    --parsable
default-resources:
  - time="12:00:00"
  - mem_mb=3740
  - tmpdir="results/snake-tmp"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 50
local-cores: 1
latency-wait: 120
cores: 2400
jobs: 450
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
rerun-trigger: mtime
cluster-generic-status-cmd: status-sacct-robust.sh
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 4000


set-threads:
  map_reads: 8
  realigner_target_creator: 4
  genomics_db_import_chromosomes: 2
  genomics_db_import_scaffold_groups: 2
  genomics_db2vcf_scattered: 2
  mark_duplicates: 8
  clip_overlaps: 8
set-resources:
  map_reads:
    mem_mb: 29920
    time: "'23:59:59'"
  mark_duplicates:
    mem_mb: 29920
    time: "'23:59:59'"
  clip_overlaps:
    mem_mb: 29920
    time: "'23:59:59'"
  make_gvcf_sections:
    mem_mb: 3600
    time: "'23:59:59'"
  genomics_db_import_chromosomes:
    mem_mb: 7480
    time: "'23:59:59'"
  genomics_db_import_scaffold_groups:
    mem_mb: 11000
    time: "'23:59:59'"
  genomics_db2vcf_scattered:
    mem_mb: 11000
    time: "'23:59:59'"
  multiqc_dir:
    mem_mb: 37000
  bwa_index:
    mem_mb: 37000